In [1]:
import pandas as pd

/tmp/ipykernel_1237651/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Counting under different filters

In [2]:
df = pd.read_csv("AML_drugs_assay_target_disease_mapped_relationship_tidy.csv")

In [3]:
df.head()

,disease_focused,assay_importance,parent_compound_chembl_id,parent_compound_specificity,assay_chembl_id,assay_cluster,target_chembl_id,target_uniprot_ids,OT_uniprot_id,OT_symbol,OT_overall_score
0,AML,2,CHEMBL3137309,acceptable,CHEMBL4332203,986,CHEMBL4860,"['C9JHD5', 'P10415', 'P10416', 'Q13842', 'Q161...",P10415,['BCL2'],0.622360
1,AML,2,CHEMBL3137309,acceptable,CHEMBL4264659,985,CHEMBL4860,"['C9JHD5', 'P10415', 'P10416', 'Q13842', 'Q161...",P10415,['BCL2'],0.622360
2,AML,2,CHEMBL576982,specific,CHEMBL4836766,981,CHEMBL1974,"['A0AVG9', 'B7ZLT7', 'B7ZLT8', 'F5H0A0', 'P368...",P36888,['FLT3'],0.821082
3,AML,2,CHEMBL576982,specific,CHEMBL4385972,980,CHEMBL1974,"['A0AVG9', 'B7ZLT7', 'B7ZLT8', 'F5H0A0', 'P368...",P36888,['FLT3'],0.821082
4,AML,2,CHEMBL3301622,specific,CHEMBL4815226,979,CHEMBL1974,"['A0AVG9', 'B7ZLT7', 'B7ZLT8', 'F5H0A0', 'P368...",P36888,['FLT3'],0.821082

In [4]:
df.sort_values(by=["parent_compound_specificity", "parent_compound_chembl_id"], ascending=[False, True], inplace=True)

In [5]:
df.head()

,disease_focused,assay_importance,parent_compound_chembl_id,parent_compound_specificity,assay_chembl_id,assay_cluster,target_chembl_id,target_uniprot_ids,OT_uniprot_id,OT_symbol,OT_overall_score
4322,AML,1,CHEMBL3989958,wide-used,CHEMBL4812388,913,CHEMBL2007625,Not interested!,NaN,NaN,NaN
4323,AML,1,CHEMBL3989958,wide-used,CHEMBL4812390,913,CHEMBL2007625,Not interested!,NaN,NaN,NaN
7660,AML,1,CHEMBL3989958,wide-used,CHEMBL4180690,1021,CHEMBL2007625,Not interested!,NaN,NaN,NaN
24133,AML,0,CHEMBL3989958,wide-used,CHEMBL4180691,Not AML cell lines,CHEMBL2007625,Not interested!,NaN,NaN,NaN
24134,AML,0,CHEMBL3989958,wide-used,CHEMBL4303805,Not AML cell lines,CHEMBL4303835,Not interested!,NaN,NaN,NaN

In [6]:
for idx, each_cid in enumerate(df['parent_compound_chembl_id'].unique()):
    df_temp = df[df['parent_compound_chembl_id'] == each_cid]
    print(idx, each_cid, df_temp['assay_chembl_id'].nunique(), df_temp['target_chembl_id'].nunique())

0 CHEMBL3989958 32 4
1 CHEMBL4297522 134 73
2 CHEMBL53463 12789 1254
3 CHEMBL58 1361 382
4 CHEMBL88 856 255
5 CHEMBL90555 1585 346
6 CHEMBL1117 439 201
7 CHEMBL1201506 19 2
8 CHEMBL2043437 39 19
9 CHEMBL2362016 52 17
10 CHEMBL3301622 355 301
11 CHEMBL3989908 27 7
12 CHEMBL4297610 32 6
13 CHEMBL576982 1613 526
14 CHEMBL608533 2669 1164
15 CHEMBL727 586 237
16 CHEMBL1201576 19 2
17 CHEMBL1489 481 181
18 CHEMBL178 1142 337
19 CHEMBL3137309 147 29
20 CHEMBL384467 1615 319
21 CHEMBL635 376 213
22 CHEMBL803 1804 861

In [7]:
print("In total", df['assay_chembl_id'].nunique(), df['target_chembl_id'].nunique())

In total 21242 2121

In [8]:
df_spec_accept = df[df['parent_compound_specificity'] != "wide-used"]
df_spec_accept.reset_index(drop=True, inplace=True)

In [9]:
print("In total", df_spec_accept['assay_chembl_id'].nunique(), df_spec_accept['target_chembl_id'].nunique())

In total 7552 1780

In [10]:
df_uniprot = df_spec_accept[~df_spec_accept['OT_uniprot_id'].isna()]
df_uniprot.reset_index(drop=True, inplace=True)

In [11]:
for idx, each_cid in enumerate(df_uniprot['parent_compound_chembl_id'].unique()):
    df_temp = df_uniprot[df_uniprot['parent_compound_chembl_id'] == each_cid]
    print(idx, each_cid, df_temp['assay_chembl_id'].nunique(), df_temp['target_chembl_id'].nunique())

0 CHEMBL1117 148 122
1 CHEMBL2043437 6 6
2 CHEMBL2362016 8 4
3 CHEMBL3301622 259 228
4 CHEMBL3989908 17 2
5 CHEMBL4297610 12 2
6 CHEMBL576982 1049 353
7 CHEMBL608533 1570 357
8 CHEMBL727 116 102
9 CHEMBL1489 139 113
10 CHEMBL178 240 153
11 CHEMBL3137309 56 6
12 CHEMBL384467 395 121
13 CHEMBL635 107 92
14 CHEMBL803 135 111

In [12]:
print("In total", df_uniprot['assay_chembl_id'].nunique(), df_uniprot['target_chembl_id'].nunique())

In total 2518 583

In [13]:
df_AML_cell_lines = df_spec_accept[df_spec_accept['assay_cluster'] != "Not AML cell lines"]
df_AML_cell_lines.reset_index(drop=True, inplace=True)

In [14]:
for idx, each_cid in enumerate(df_AML_cell_lines['parent_compound_chembl_id'].unique()):
    df_temp = df_AML_cell_lines[df_AML_cell_lines['parent_compound_chembl_id'] == each_cid]
    print(idx, each_cid, df_temp['assay_chembl_id'].nunique(), df_temp['target_chembl_id'].nunique(), df_temp['assay_cluster'].nunique())

0 CHEMBL1117 140 91 140
1 CHEMBL1201506 10 2 10
2 CHEMBL2043437 22 12 14
3 CHEMBL2362016 26 5 20
4 CHEMBL3301622 309 285 23
5 CHEMBL3989908 14 2 7
6 CHEMBL4297610 9 4 7
7 CHEMBL576982 1354 496 955
8 CHEMBL608533 1901 506 1389
9 CHEMBL727 153 93 149
10 CHEMBL1201576 10 2 10
11 CHEMBL1489 134 89 132
12 CHEMBL178 265 128 235
13 CHEMBL3137309 52 13 42
14 CHEMBL384467 361 135 283
15 CHEMBL635 165 101 159
16 CHEMBL803 270 124 217

In [15]:
print("In total", df_AML_cell_lines['assay_chembl_id'].nunique(), df_AML_cell_lines['target_chembl_id'].nunique(), df_AML_cell_lines['assay_cluster'].nunique())

In total 2946 724 2036

In [16]:
df_uniprot_AML_cell_lines = df_AML_cell_lines[~df_AML_cell_lines['OT_uniprot_id'].isna()]
df_uniprot_AML_cell_lines.reset_index(drop=True, inplace=True)

In [17]:
for idx, each_cid in enumerate(df_uniprot_AML_cell_lines['parent_compound_chembl_id'].unique()):
    df_temp = df_uniprot_AML_cell_lines[df_uniprot_AML_cell_lines['parent_compound_chembl_id'] == each_cid]
    print(idx, each_cid, df_temp['assay_chembl_id'].nunique(), df_temp['target_chembl_id'].nunique(), df_temp['assay_cluster'].nunique())

0 CHEMBL1117 60 60 60
1 CHEMBL2043437 6 6 2
2 CHEMBL2362016 1 1 1
3 CHEMBL3301622 243 226 18
4 CHEMBL3989908 14 2 7
5 CHEMBL4297610 5 2 3
6 CHEMBL576982 947 352 692
7 CHEMBL608533 1502 354 1080
8 CHEMBL727 61 60 60
9 CHEMBL1489 59 59 58
10 CHEMBL178 93 77 86
11 CHEMBL3137309 37 5 28
12 CHEMBL384467 151 82 132
13 CHEMBL635 66 65 62
14 CHEMBL803 72 67 66

In [18]:
print("In total", df_uniprot_AML_cell_lines['assay_chembl_id'].nunique(), df_uniprot_AML_cell_lines['target_chembl_id'].nunique(), df_uniprot_AML_cell_lines['assay_cluster'].nunique())

In total 1913 482 1357

In [19]:
'Not AML cell lines' in df_uniprot_AML_cell_lines['assay_cluster'].unique()

False

In [20]:
for idx, each_cid in enumerate(df_spec_accept['parent_compound_chembl_id'].unique()):
    df_temp = df_spec_accept[df_spec_accept['parent_compound_chembl_id'] == each_cid]
    for jdx, each_assay_import in enumerate(df_temp['assay_importance'].unique()):
        df_temp_import = df_temp[df_temp['assay_importance'] == each_assay_import]
        num_assay = df_temp_import['assay_chembl_id'].nunique()
        num_target = df_temp_import['target_chembl_id'].nunique()
        num_cluster = df_temp_import['assay_cluster'].nunique()
        if "Not AML cell lines" in df_temp_import['assay_cluster'].unique():
            num_cluster -= 1
        print(idx, each_cid, each_assay_import, f"{num_assay} ({num_target}) \\newline ({num_cluster} clusters)")

0 CHEMBL1117 2 60 (60) \newline (60 clusters)
0 CHEMBL1117 1 168 (97) \newline (80 clusters)
0 CHEMBL1117 0 211 (52) \newline (0 clusters)
1 CHEMBL1201506 1 10 (2) \newline (10 clusters)
1 CHEMBL1201506 0 9 (2) \newline (0 clusters)
2 CHEMBL2043437 2 6 (6) \newline (2 clusters)
2 CHEMBL2043437 1 16 (6) \newline (12 clusters)
2 CHEMBL2043437 0 17 (8) \newline (0 clusters)
3 CHEMBL2362016 2 1 (1) \newline (1 clusters)
3 CHEMBL2362016 1 32 (8) \newline (19 clusters)
3 CHEMBL2362016 0 19 (11) \newline (0 clusters)
4 CHEMBL3301622 2 243 (226) \newline (18 clusters)
4 CHEMBL3301622 1 82 (67) \newline (6 clusters)
4 CHEMBL3301622 0 30 (15) \newline (0 clusters)
5 CHEMBL3989908 2 14 (2) \newline (7 clusters)
5 CHEMBL3989908 1 3 (2) \newline (0 clusters)
5 CHEMBL3989908 0 10 (5) \newline (0 clusters)
6 CHEMBL4297610 2 5 (2) \newline (3 clusters)
6 CHEMBL4297610 1 11 (3) \newline (4 clusters)
6 CHEMBL4297610 0 16 (4) \newline (0 clusters)
7 CHEMBL576982 2 947 (352) \newline (692 clusters)
7 CHEMBL576982 1 509 (162) \newline (264 clusters)
7 CHEMBL576982 0 157 (32) \newline (0 clusters)
8 CHEMBL608533 2 1502 (354) \newline (1080 clusters)
8 CHEMBL608533 1 467 (169) \newline (311 clusters)
8 CHEMBL608533 0 700 (657) \newline (0 clusters)
9 CHEMBL727 2 61 (60) \newline (60 clusters)
9 CHEMBL727 1 147 (77) \newline (89 clusters)
9 CHEMBL727 0 378 (106) \newline (0 clusters)
10 CHEMBL1201576 1 10 (2) \newline (10 clusters)
10 CHEMBL1201576 0 9 (2) \newline (0 clusters)
11 CHEMBL1489 2 59 (59) \newline (58 clusters)
11 CHEMBL1489 1 155 (85) \newline (74 clusters)
11 CHEMBL1489 0 267 (41) \newline (0 clusters)
12 CHEMBL178 2 93 (77) \newline (86 clusters)
12 CHEMBL178 1 319 (140) \newline (149 clusters)
12 CHEMBL178 0 730 (140) \newline (0 clusters)
13 CHEMBL3137309 2 37 (5) \newline (28 clusters)
13 CHEMBL3137309 1 34 (13) \newline (14 clusters)
13 CHEMBL3137309 0 76 (16) \newline (0 clusters)
14 CHEMBL384467 2 151 (82) \newline (132 clusters)
14 CHEMBL384467 1 454 (107) \newline (151 clusters)
14 CHEMBL384467 0 1010 (154) \newline (0 clusters)
15 CHEMBL635 2 66 (65) \newline (62 clusters)
15 CHEMBL635 1 140 (70) \newline (97 clusters)
15 CHEMBL635 0 170 (91) \newline (0 clusters)
16 CHEMBL803 2 72 (67) \newline (66 clusters)
16 CHEMBL803 1 261 (108) \newline (152 clusters)
16 CHEMBL803 0 1471 (699) \newline (0 clusters)

In [21]:
for important in df_spec_accept['assay_importance'].unique():
    df_spec_accept_import = df_spec_accept[df_spec_accept['assay_importance'] == important]
    
    num_assay = df_spec_accept_import['assay_chembl_id'].nunique()
    num_target = df_spec_accept_import['target_chembl_id'].nunique()
    num_cluster = df_spec_accept_import['assay_cluster'].nunique()
    if "Not AML cell lines" in df_spec_accept_import['assay_cluster'].unique():
        num_cluster -= 1

    print("In total", important, f"{num_assay} ({num_target}) \\newline ({num_cluster} clusters)")

In total 2 1913 (482) \newline (1357 clusters)
In total 1 1638 (413) \newline (682 clusters)
In total 0 4001 (974) \newline (0 clusters)

# Case study

In [24]:
df[df['parent_compound_chembl_id'] == 'CHEMBL2362016']

,disease_focused,assay_importance,parent_compound_chembl_id,parent_compound_specificity,assay_chembl_id,assay_cluster,target_chembl_id,target_uniprot_ids,OT_uniprot_id,OT_symbol,OT_overall_score
3258,AML,2,CHEMBL2362016,specific,CHEMBL935686,1040,CHEMBL2403,"['O95840', 'Q96IJ2', 'Q9H2Z5', 'Q9NNW7', 'Q9NZ...",Q9NNW7,['TXNRD2'],0.005770
3466,AML,1,CHEMBL2362016,specific,CHEMBL931514,Not AML cell lines,CHEMBL1927,"['B7Z1F4', 'B7Z3Y8', 'B7Z904', 'E9PMY9', 'F5H7...",Q16881,['TXNRD1'],0.571059
3831,AML,1,CHEMBL2362016,specific,CHEMBL1614544,Not AML cell lines,CHEMBL1293235,"['B4DI32', 'D3DVB0', 'D6RAQ3', 'E7EUI9', 'P025...",P02545,['LMNA'],0.186290
4179,AML,1,CHEMBL2362016,specific,CHEMBL931515,Not AML cell lines,CHEMBL2403,"['O95840', 'Q96IJ2', 'Q9H2Z5', 'Q9NNW7', 'Q9NZ...",Q9NNW7,['TXNRD2'],0.005770
4180,AML,1,CHEMBL2362016,specific,CHEMBL931516,Not AML cell lines,CHEMBL2403,"['O95840', 'Q96IJ2', 'Q9H2Z5', 'Q9NNW7', 'Q9NZ...",Q9NNW7,['TXNRD2'],0.005770
4181,AML,1,CHEMBL2362016,specific,CHEMBL931517,Not AML cell lines,CHEMBL2403,"['O95840', 'Q96IJ2', 'Q9H2Z5', 'Q9NNW7', 'Q9NZ...",Q9NNW7,['TXNRD2'],0.005770
4240,AML,1,CHEMBL2362016,specific,CHEMBL2354221,Not AML cell lines,CHEMBL1075138,"['Q2HXX4', 'Q86TV8', 'Q96BK7', 'Q9NUW8', 'Q9NZ...",Q9NUW8,['TDP1'],0.001478
4241,AML,1,CHEMBL2362016,specific,CHEMBL2354254,Not AML cell lines,CHEMBL1075138,"['Q2HXX4', 'Q86TV8', 'Q96BK7', 'Q9NUW8', 'Q9NZ...",Q9NUW8,['TDP1'],0.001478
4396,AML,1,CHEMBL2362016,specific,CHEMBL3423582,828,CHEMBL3879801,no_uni_id!,NaN,NaN,NaN
4930,AML,1,CHEMBL2362016,specific,CHEMBL3292697,619,CHEMBL383,no_uni_id!,NaN,NaN,NaN
4931,AML,1,CHEMBL2362016,specific,CHEMBL3296163,619,CHEMBL383,no_uni_id!,NaN,NaN,NaN
5529,AML,1,CHEMBL2362016,specific,CHEMBL1909309,350,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5542,AML,1,CHEMBL2362016,specific,CHEMBL1909308,349,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5553,AML,1,CHEMBL2362016,specific,CHEMBL1909320,348,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5564,AML,1,CHEMBL2362016,specific,CHEMBL1909316,347,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5575,AML,1,CHEMBL2362016,specific,CHEMBL1909307,346,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5586,AML,1,CHEMBL2362016,specific,CHEMBL1909315,345,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5597,AML,1,CHEMBL2362016,specific,CHEMBL1909317,344,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5608,AML,1,CHEMBL2362016,specific,CHEMBL1909310,343,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5619,AML,1,CHEMBL2362016,specific,CHEMBL1909312,342,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5630,AML,1,CHEMBL2362016,specific,CHEMBL1909314,341,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5641,AML,1,CHEMBL2362016,specific,CHEMBL1909313,340,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5653,AML,1,CHEMBL2362016,specific,CHEMBL1909318,339,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5664,AML,1,CHEMBL2362016,specific,CHEMBL1909319,338,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5675,AML,1,CHEMBL2362016,specific,CHEMBL1909311,337,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
5931,AML,1,CHEMBL2362016,specific,CHEMBL1697730,284,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
7247,AML,1,CHEMBL2362016,specific,CHEMBL935685,1362,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7248,AML,1,CHEMBL2362016,specific,CHEMBL935687,1362,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7249,AML,1,CHEMBL2362016,specific,CHEMBL936488,1362,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7250,AML,1,CHEMBL2362016,specific,CHEMBL931509,1362,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7251,AML,1,CHEMBL2362016,specific,CHEMBL931518,1361,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7252,AML,1,CHEMBL2362016,specific,CHEMBL931519,1361,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7253,AML,1,CHEMBL2362016,specific,CHEMBL931520,1361,CHEMBL6035,"['O89049', 'Q5U344', 'Q9JKZ3', 'Q9JKZ4', 'Q9R1...",NaN,NaN,NaN
7677,AML,0,CHEMBL2362016,specific,CHEMBL931510,Not AML cell lines,CHEMBL612545,no_uni_id!,NaN,NaN,NaN
7678,AML,0,CHEMBL2362016,specific,CHEMBL931511,Not AML cell lines,CHEMBL387,no_uni_id!,NaN,NaN,NaN
7679,AML,0,CHEMBL2362016,specific,CHEMBL931512,Not AML cell lines,CHEMBL387,no_uni_id!,NaN,NaN,NaN
7680,AML,0,CHEMBL2362016,specific,CHEMBL931513,Not AML cell lines,CHEMBL387,no_uni_id!,NaN,NaN,NaN
7681,AML,0,CHEMBL2362016,specific,CHEMBL1697722,Not AML cell lines,CHEMBL1697861,no_uni_id!,NaN,NaN,NaN
7682,AML,0,CHEMBL2362016,specific,CHEMBL1794345,Not AML cell lines,CHEMBL364,no_uni_id!,NaN,NaN,NaN
7683,AML,0,CHEMBL2362016,specific,CHEMBL1794580,Not AML cell lines,CHEMBL364,no_uni_id!,NaN,NaN,NaN
7684,AML,0,CHEMBL2362016,specific,CHEMBL1964081,Not AML cell lines,CHEMBL2007624,['P25094'],NaN,NaN,NaN
7685,AML,0,CHEMBL2362016,specific,CHEMBL3215169,Not AML cell lines,CHEMBL612545,no_uni_id!,NaN,NaN,NaN
7686,AML,0,CHEMBL2362016,specific,CHEMBL3214913,Not AML cell lines,CHEMBL612545,no_uni_id!,NaN,NaN,NaN
7687,AML,0,CHEMBL2362016,specific,CHEMBL3214970,Not AML cell lines,CHEMBL612545,no_uni_id!,NaN,NaN,NaN
7688,AML,0,CHEMBL2362016,specific,CHEMBL3296164,Not AML cell lines,CHEMBL3879801,no_uni_id!,NaN,NaN,NaN
7689,AML,0,CHEMBL2362016,specific,CHEMBL3296165,Not AML cell lines,CHEMBL399,no_uni_id!,NaN,NaN,NaN
7690,AML,0,CHEMBL2362016,specific,CHEMBL3296166,Not AML cell lines,CHEMBL395,no_uni_id!,NaN,NaN,NaN
7691,AML,0,CHEMBL2362016,specific,CHEMBL4029349,Not AML cell lines,CHEMBL372,no_uni_id!,NaN,NaN,NaN
7692,AML,0,CHEMBL2362016,specific,CHEMBL4029350,Not AML cell lines,CHEMBL372,no_uni_id!,NaN,NaN,NaN
7693,AML,0,CHEMBL2362016,specific,CHEMBL4303805,Not AML cell lines,CHEMBL4303835,no_uni_id!,NaN,NaN,NaN
7694,AML,0,CHEMBL2362016,specific,CHEMBL4495582,Not AML cell lines,CHEMBL4523582,['P0DTD1'],NaN,NaN,NaN
7695,AML,0,CHEMBL2362016,specific,CHEMBL4513082,Not AML cell lines,CHEMBL4303835,no_uni_id!,NaN,NaN,NaN